### PR TITLE
Update to use @match statements

### PR DESCRIPTION
**Pull request by DaJoNel**
Use `@match` statements so that the script loads in Tampermonkey.

### CODE REVIEW

**Comment by mapomatic** [comment]
@DaJoNel is it not loading for you in TM without the match statements?

**Comment by DaJoNel** [comment]
@mapomatic No, the script hasn’t loaded for awhile now and hasn’t appeared in list of available scripts when on a WME page. When I looked at the source, I saw a Tampermonkey warning on the @include line saying that @match should be used. When I updated the code, the script loaded without issue.

**Comment by mapomatic** [comment]
Are you using WMEPH prod in WME beta, or vice versa?  I updated it recently so that WMEPH (prod) only works in prod WME, and WMEPH beta only works in beta WME.

**Comment by mapomatic** [comment]
@DaJoNel I should clarify... the code for WMEPH prod/beta may actually "work" in either version of WME (at times, depending on their state), but I changed the include statements so they would only run in those specific WME versions.  That was intentional, at least while we work out some issues.  As far as I know, TM still continues (and plans to continue) support for include statements despite the linter warnings.

**Comment by mapomatic** [comment]
Closing this issue for now.  We can revisit if include statements are indeed disallowed by TM.

**Comment by mapomatic** [comment]
Closing this issue for now. We can revisit if include statements are indeed disallowed by TM.

**Comment by DaJoNel** [comment]
I didn't realize there was a beta version of the script so I was trying to use the regular version with beta WME. Thanks for the explanation!

**Pull request closed without merging**
